#!/usr/bin/env python3
"""
scripts/build.py - Deterministic build script for Spotify Local FLAC frontend.

Consolidates modular sources in spicetify/src/ into:
  - spicetify/Extensions/local-flac-player.js
  - spicetify/CustomApps/local-flac/index.js
  - spicetify/CustomApps/local-flac/style.css
"""

import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "spicetify" / "src"
EXT_DIR = REPO_ROOT / "spicetify" / "Extensions"
APP_DIR = REPO_ROOT / "spicetify" / "CustomApps" / "local-flac"


def build() -> None:
    # 1. Verify source files exist
    required_sources = ["styles.css", "api.js", "player.js", "app.js", "extension.js"]
    for src in required_sources:
        path = SRC_DIR / src
        if not path.is_file():
            print(f"Error: Missing required source file: {path}", file=sys.stderr)
            sys.exit(1)

    # 2. Read source files
    styles_css = (SRC_DIR / "styles.css").read_text(encoding="utf-8")
    api_js = (SRC_DIR / "api.js").read_text(encoding="utf-8")
    player_js = (SRC_DIR / "player.js").read_text(encoding="utf-8")
    app_js = (SRC_DIR / "app.js").read_text(encoding="utf-8")
    extension_js = (SRC_DIR / "extension.js").read_text(encoding="utf-8")

    # Ensure output directories exist
    EXT_DIR.mkdir(parents=True, exist_ok=True)
    APP_DIR.mkdir(parents=True, exist_ok=True)

    # 3. Build CustomApp style.css
    target_app_css = APP_DIR / "style.css"
    target_app_css.write_text(styles_css, encoding="utf-8")
    print(f"Built: {target_app_css.relative_to(REPO_ROOT)} ({len(styles_css)} bytes)")

    # 4. Build CustomApp index.js
    custom_app_code = f"""// Spotify Local FLAC - Custom App
// Auto-generated by scripts/build.py from spicetify/src/. Do not edit directly.

(function() {{
  "use strict";

{api_js}

{app_js}

  const LocalFlacApp = createLocalFlacComponent();
  window.LocalFlacApp = LocalFlacApp;
  window.render = function() {{
    return Spicetify.React.createElement(LocalFlacApp, null);
  }};
}})();

function render() {{
  return window.render ? window.render() : null;
}}
"""
    target_app_js = APP_DIR / "index.js"
    target_app_js.write_text(custom_app_code, encoding="utf-8")
    print(f"Built: {target_app_js.relative_to(REPO_ROOT)} ({len(custom_app_code)} bytes)")

    # 5. Build Extension local-flac-player.js
    css_json = json.dumps(styles_css)
    extension_bundle = f"""// Spotify Local FLAC - Production Extension Bundle
// Auto-generated by scripts/build.py from spicetify/src/. Do not edit directly.

(function initSpotifyLocalFlacBundle() {{
  "use strict";

  const __LOCAL_FLAC_CSS__ = {css_json};

{api_js}

{player_js}

{app_js}

{extension_js}
}})();
"""
    target_ext = EXT_DIR / "local-flac-player.js"
    target_ext.write_text(extension_bundle, encoding="utf-8")
    os.chmod(target_ext, 0o600)
    print(f"Built: {target_ext.relative_to(REPO_ROOT)} ({len(extension_bundle)} bytes, mode 0600)")


if __name__ == "__main__":
    build()
